version: '1.0'

services:
  postgres:
    image: postgres:15
    container_name: 'postgres-db'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres
    ports:
      - 5432:5432

  backend:
    image: 'mujammed04/final-project'
    container_name: 'backend'
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
    ports:
      - 8080:8080